language: csharp
sudo: required
dist: xenial
solution: System.Extension.EntityFrameworkCore.sln
dotnet: 3.1.101
mono: none

#matrix:
#  include:
#  - dotnet: 2.2
#  - os: linux
#    dist: trusty # Ubuntu 14.04
#    sudo: required
#  - os: osx
#    osx_image: xcode8.3 # macOS 10.12
    
# Run the build script
script:
  - dotnet --info
  - dotnet restore System.Extension.EntityFrameworkCore.sln
  - dotnet build System.Extension.EntityFrameworkCore.sln